# Generated by Django 3.1.7 on 2021-03-15 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('producer', 'Производитель'), ('broker', 'Маклер')], max_length=20, verbose_name='Игровая роль')),
                ('position', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('game_type', models.CharField(choices=[('normal', 'Стандартная'), ('hard', 'Сложная')], default='normal', max_length=15)),
                ('number_of_players', models.CharField(choices=[('12-14', '12-14 Игроков'), ('15-20', '15-20 Игроков'), ('21-25', '21-25 Игроков'), ('26-30', '26-30 Игроков'), ('31-35', '31-35 Игроков')], default='12-14', max_length=20)),
                ('number_of_brokers', models.PositiveSmallIntegerField(default=3)),
                ('turn_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('created', 'Сессия создана'), ('started', 'Сессия заполнена'), ('finished', 'Сессия закончилась')], default='created', max_length=15)),
                ('broker_starting_balance', models.PositiveSmallIntegerField()),
                ('producer_starting_balance', models.PositiveSmallIntegerField()),
                ('transaction_limit', models.PositiveSmallIntegerField(default=2000)),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Neverfall', 'Неверфол'), ('Tortuga', 'Тортуга'), ('Wemshire', 'Вемшир'), ('Ivo', 'Айво'), ('Alendor', 'Алендор'), ('Etroi', 'Этруа')], max_length=20, verbose_name='Расположение')),
                ('balance', models.PositiveIntegerField()),
                ('billets_produced', models.PositiveIntegerField()),
                ('billets_stored', models.PositiveIntegerField()),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='game.player')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.session'),
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Neverfall', 'Неверфол'), ('Tortuga', 'Тортуга'), ('Wemshire', 'Вемшир'), ('Ivo', 'Айво'), ('Alendor', 'Алендор'), ('Etroi', 'Этруа')], max_length=20, verbose_name='Расположение')),
                ('balance', models.PositiveIntegerField()),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker', to='game.player')),
            ],
            options={
                'verbose_name': 'Маклер',
                'verbose_name_plural': 'Маклеры',
            },
        ),
    ]
