# Generated by Django 3.1.7 on 2021-03-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Neverfall', 'Неверфол'), ('Tortuga', 'Тортуга'), ('Wemshire', 'Вемшир'), ('Ivo', 'Айво'), ('Alendor', 'Алендор'), ('Etroi', 'Этруа')], max_length=20, verbose_name='Расположение')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('is_bankrupt', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Маклер',
                'verbose_name_plural': 'Маклеры',
            },
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150, verbose_name='Ник пользователя')),
                ('role', models.CharField(choices=[('producer', 'Производитель'), ('broker', 'Маклер')], max_length=20, verbose_name='Игровая роль')),
                ('position', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Место')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='ProducerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Neverfall', 'Неверфол'), ('Tortuga', 'Тортуга'), ('Wemshire', 'Вемшир'), ('Ivo', 'Айво'), ('Alendor', 'Алендор'), ('Etroi', 'Этруа')], max_length=20, verbose_name='Расположение')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('billets_produced', models.PositiveIntegerField(default=0)),
                ('billets_stored', models.PositiveIntegerField(default=0)),
                ('is_bankrupt', models.BooleanField(default=False)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'producer'}, on_delete=django.db.models.deletion.CASCADE, related_name='producer', to='game.playermodel')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('game_type', models.CharField(choices=[('normal', 'Стандартная'), ('hard', 'Сложная')], default='normal', max_length=15)),
                ('number_of_players', models.CharField(choices=[('12-14', '12-14 Игроков'), ('15-20', '15-20 Игроков'), ('21-25', '21-25 Игроков'), ('26-30', '26-30 Игроков'), ('31-35', '31-35 Игроков')], default='12-14', max_length=20)),
                ('number_of_brokers', models.PositiveSmallIntegerField(editable=False)),
                ('crown_balance', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('turn_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('created', 'Сессия создана'), ('started', 'Сессия заполнена'), ('finished', 'Сессия закончилась')], default='created', editable=False, max_length=15)),
                ('broker_starting_balance', models.PositiveSmallIntegerField(editable=False)),
                ('producer_starting_balance', models.PositiveSmallIntegerField(editable=False)),
                ('transaction_limit', models.PositiveSmallIntegerField(default=2000, editable=False)),
                ('current_turn', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Текущий ход')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('transporting_cost', models.PositiveSmallIntegerField(default=0)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.brokermodel')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.producermodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='game.sessionmodel')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddField(
            model_name='playermodel',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.sessionmodel', verbose_name='Сессия'),
        ),
        migrations.AddField(
            model_name='brokermodel',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'broker'}, on_delete=django.db.models.deletion.CASCADE, related_name='broker', to='game.playermodel'),
        ),
    ]
