# Generated by Django 3.1.7 on 2021-03-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='broker_starting_balance',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='number_of_brokers',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='producer_starting_balance',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('created', 'Сессия создана'), ('started', 'Сессия заполнена'), ('finished', 'Сессия закончилась')], default='created', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='session',
            name='transaction_limit',
            field=models.PositiveSmallIntegerField(default=2000, editable=False),
        ),
    ]
