# Generated by Django 3.1.7 on 2021-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokermodel',
            name='city',
            field=models.CharField(choices=[('NF', 'Неверфол'), ('TT', 'Тортуга'), ('WS', 'Вемшир'), ('IV', 'Айво'), ('AD', 'Алендор'), ('ET', 'Этруа')], max_length=20, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='city',
            field=models.CharField(choices=[('NF', 'Неверфол'), ('TT', 'Тортуга'), ('WS', 'Вемшир'), ('IV', 'Айво'), ('AD', 'Алендор'), ('ET', 'Этруа')], max_length=20, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='current_turn',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Текущий ход'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='status',
            field=models.CharField(choices=[('created', 'Сессия создана'), ('started', 'Сессия заполнена'), ('finished', 'Сессия закончилась')], default='created', max_length=15),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transporting_cost',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
