# Generated by Django 3.1.7 on 2021-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('game', '0003_auto_20210318_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermodel',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='playermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='authorization.usermodel', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='brokermodel',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'broker'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker', to='game.playermodel'),
        ),
        migrations.AlterField(
            model_name='brokermodel',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker', to='game.sessionmodel', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='nickname',
            field=models.CharField(default='', max_length=100, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='role',
            field=models.CharField(choices=[('unassigned', 'Не назначена'), ('producer', 'Производитель'), ('broker', 'Маклер')], default='unassigned', max_length=20, verbose_name='Игровая роль'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='player',
            field=models.ForeignKey(limit_choices_to={'role': 'producer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to='game.playermodel'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to='game.sessionmodel', verbose_name='Сессия'),
        ),
    ]
