# Generated by Django 3.1.7 on 2021-03-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20210318_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermodel',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.RemoveField(
            model_name='brokermodel',
            name='session',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='session',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='game.sessionmodel', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='brokermodel',
            name='city',
            field=models.CharField(choices=[('unassigned', 'Не назначен'), ('NF', 'Неверфол'), ('TT', 'Тортуга'), ('WS', 'Вемшир'), ('IV', 'Айво'), ('AD', 'Алендор'), ('ET', 'Этруа')], max_length=20, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='brokermodel',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker', to='game.playermodel'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='city',
            field=models.CharField(choices=[('unassigned', 'Не назначен'), ('NF', 'Неверфол'), ('TT', 'Тортуга'), ('WS', 'Вемшир'), ('IV', 'Айво'), ('AD', 'Алендор'), ('ET', 'Этруа')], max_length=20, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to='game.playermodel'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='crown_balance',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transporting_cost',
            field=models.PositiveSmallIntegerField(default=10, editable=False),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='turn',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
    ]
