# Generated by Django 3.1.7 on 2021-03-24 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0006_auto_20210322_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokermodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='billets_produced',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producermodel',
            name='billets_stored',
            field=models.IntegerField(default=0),
        ),
    ]
