# Generated by Django 3.1.7 on 2021-04-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210324_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokermodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='id',
        ),
        migrations.AddField(
            model_name='brokermodel',
            name='playermodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.playermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playermodel',
            name='ended_turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producermodel',
            name='playermodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='game.playermodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionmodel',
            name='turn_phase',
            field=models.CharField(choices=[('negotiation', 'Этап переговоров'), ('transaction', 'Этап заключения сделок')], default='negotiation', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Сделка на рассмотрении'), ('accepted', 'Сделка согласована'), ('denied', 'Сделка отклонена')], default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='session',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='game.sessionmodel', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='number_of_players',
            field=models.CharField(choices=[('12-14', '12-14 Игроков'), ('15-20', '15-20 Игроков'), ('21-25', '21-25 Игроков'), ('26-30', '26-30 Игроков'), ('31-35', '31-35 Игроков')], default='12-14', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='status',
            field=models.CharField(choices=[('initialized', 'Сессия инициализирована'), ('created', 'Сессия создана'), ('started', 'Сессия запущена'), ('finished', 'Сессия закончилась')], default='initialized', max_length=15),
        ),
    ]
