# Generated by Django 3.1.7 on 2021-04-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210406_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokermodel',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='brokermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='brokermodel',
            name='is_bankrupt',
        ),
        migrations.RemoveField(
            model_name='brokermodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='brokermodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='playermodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='is_bankrupt',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='player',
        ),
        migrations.RemoveField(
            model_name='producermodel',
            name='status',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='city',
            field=models.CharField(choices=[('unassigned', 'Не назначен'), ('IV', 'Айво'), ('WS', 'Вемшир'), ('TT', 'Тортуга'), ('AD', 'Алендор'), ('NF', 'Неверфол'), ('ET', 'Этруа')], default='unassigned', max_length=20, verbose_name='Расположение'),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='status',
            field=models.CharField(default='OK', editable=False, max_length=20, verbose_name='Статус банкротства'),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='broker_starting_balance',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='number_of_brokers',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='producer_starting_balance',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='turn_phase',
            field=models.CharField(choices=[('negotiation', 'Этап переговоров'), ('transaction', 'Этап заключения сделок')], default='negotiation', editable=False, max_length=20),
        ),
    ]
