# Generated by Django 3.1.7 on 2021-04-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210408_1017'),
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertokenmodel',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='game.playermodel', verbose_name='player'),
        ),
        migrations.DeleteModel(
            name='PlayerModel',
        ),
    ]
