# Generated by Django 3.1.7 on 2021-03-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210324_0858'),
        ('authorization', '0002_auto_20210319_1007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
